CEO_ACCESS_TOKEN = "Vijay"
OPENAI_API_KEY = "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"
