CEO_ACCESS_TOKEN = "Vijay"
OPENAI_API_KEY = "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"
